# Generated by Django 2.2.16 on 2022-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220912_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
